import { blockById } from "./blocks"
import type { Contribution, Recipe, SimHints } from "./recipe"

export type VirtualFile = { path: string; content: string; mode?: string }
export type CompileResult = {
	files: VirtualFile[]
	packages: string[]
	lbFlags: Record<string, string>
	sim: SimHints & { desktopIcons: { label: string; icon: string }[] }
	estimatedMb: number
}

const slug = (s: string) =>
	s
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "-")
		.replace(/^-|-$/g, "") || "myos"

/** Pure: recipe in, live-build tree out. No filesystem, no network. */
export function compileRecipe(recipe: Recipe): CompileResult {
	const contributions: Contribution[] = recipe.blocks.map((b) => {
		const def = blockById(b.def)
		return def ? def.emit(b.cfg) : {}
	})

	const packages = [
		...new Set(contributions.flatMap((c) => c.packages ?? [])),
	].sort()
	const remove = new Set(contributions.flatMap((c) => c.removePackages ?? []))
	const finalPackages = packages.filter((p) => !remove.has(p))

	const lbFlags = Object.assign({}, ...contributions.map((c) => c.lbFlags ?? {})) as Record<
		string,
		string
	>

	const enable = [...new Set(contributions.flatMap((c) => c.services?.enable ?? []))]
	const disable = [...new Set(contributions.flatMap((c) => c.services?.disable ?? []))]
	const hooks = contributions.flatMap((c) => c.hooks ?? [])

	const sim = Object.assign(
		{ panel: "bottom", windowStyle: "rounded", accent: "#2783DE", desktopIcons: [] },
		...contributions.map((c) => {
			const { desktopIcons, ...rest } = c.sim ?? {}
			return rest
		}),
	) as CompileResult["sim"]
	sim.desktopIcons = contributions.flatMap((c) => c.sim?.desktopIcons ?? [])

	const estimatedMb = contributions.reduce((n, c) => n + (c.sizeMb ?? 0), 0)
	const id = slug(recipe.name)

	const files: VirtualFile[] = [
		{
			path: "auto/config",
			mode: "755",
			content:
				"#!/bin/sh\n# Generated by ZenvX Framework. Do not edit by hand.\nset -e\n\nlb config noauto \\\n" +
				Object.entries(lbFlags)
					.map(([k, v]) => `  --${k.replace(/_/g, "-")} "${v}" \\`)
					.join("\n") +
				`\n  --iso-application "${recipe.name}" \\\n  --iso-volume "${recipe.name}" \\\n  "\${@}"\n`,
		},
		{
			path: "config/package-lists/zenvx.list.chroot",
			content: finalPackages.join("\n") + "\n",
		},
		{
			path: "config/includes.chroot/etc/os-release",
			content: [
				`NAME="${recipe.name}"`,
				`PRETTY_NAME="${recipe.name}${recipe.codename ? ` (${recipe.codename})` : ""}"`,
				`ID=${id}`,
				"ID_LIKE=debian",
				'VERSION="0.1"',
				`HOME_URL="https://zenvx.dev/distros/${id}"`,
				'BUILD_ID="zenvx-framework"',
				"",
			].join("\n"),
		},
		{
			path: "config/includes.chroot/etc/zenvx/recipe.json",
			content: JSON.stringify(recipe, null, 2) + "\n",
		},
		{
			path: "config/hooks/normal/9000-zenvx.hook.chroot",
			mode: "755",
			content: [
				"#!/bin/sh",
				"# Generated by ZenvX Framework.",
				"set -e",
				"",
				...hooks,
				...enable.map((s) => `systemctl enable ${s} || true`),
				...disable.map((s) => `systemctl disable ${s} || true`),
				"",
			].join("\n"),
		},
		{
			path: "build.sh",
			mode: "755",
			content:
				"#!/bin/sh\nset -e\nlb clean --purge\n./auto/config\nlb build 2>&1 | tee build.log\n",
		},
	]

	for (const c of contributions) {
		for (const f of c.files ?? []) {
			files.push({ ...f, path: `config/includes.chroot/${f.path}` })
		}
	}

	return { files, packages: finalPackages, lbFlags, sim, estimatedMb }
}
