#!/usr/bin/env node
/**
 * ZenvX demo builder.
 *
 * Reads examples/kid-first-distro.zenvx.json and writes the real live-build
 * tree for AaruOS into demo/aaruos/. This is a dependency-free port of
 * @zenvx/schema's compiler so the demo runs with plain `node`, no install.
 * Its output is byte-identical to compileRecipe() from @zenvx/schema.
 *
 *   node demo/build-demo.mjs
 *   cd demo/aaruos && sudo ./build.sh   # needs Debian + live-build
 */
import { mkdir, writeFile, chmod, rm } from "node:fs/promises"
import { dirname, join, resolve } from "node:path"
import { readFileSync } from "node:fs"

const ROOT = resolve(import.meta.dirname, "..")
const OUT = join(ROOT, "demo", "aaruos")
const recipe = JSON.parse(
	readFileSync(join(ROOT, "examples", "kid-first-distro.zenvx.json"), "utf8"),
)

/* ---- minimal block catalog: only what the demo recipe uses ------------- */
const wallpapers = {
	space: "linear-gradient(160deg,#101828,#2783DE)",
	forest: "linear-gradient(160deg,#14281f,#46A171)",
	sunset: "linear-gradient(160deg,#3a1c1c,#D5803B)",
	plain: "linear-gradient(160deg,#202020,#383836)",
}

const app = (label, packages, sizeMb) => ({
	emit: () => ({
		packages,
		sim: { desktopIcons: [{ label }] },
		sizeMb,
	}),
})

const BLOCKS = {
	"base.debian-stable": {
		emit: (cfg) => ({
			lbFlags: {
				distribution: "trixie",
				architectures: cfg.arch ?? "amd64",
				archive_areas: "main contrib non-free-firmware",
				binary_images: "iso-hybrid",
			},
			packages: ["linux-image-amd64", "live-boot", "systemd-sysv", "network-manager"],
			sizeMb: 720,
		}),
	},
	"desktop.xfce": {
		emit: (cfg) => ({
			packages: ["xfce4", "xfce4-terminal", "thunar", "lightdm", "xserver-xorg"],
			services: { enable: ["lightdm"] },
			sim: { panel: cfg.panelPosition ?? "bottom", windowStyle: "square" },
			sizeMb: 420,
		}),
	},
	"look.theme": {
		emit: (cfg) => ({
			packages: ["papirus-icon-theme", "fonts-inter"],
			files: [
				{
					path: "etc/zenvx/theme.conf",
					content: `accent=${cfg.accent ?? "#2783DE"}\nwallpaper=${cfg.wallpaper ?? "space"}\ndark=${cfg.darkMode !== false}\n`,
				},
			],
			sim: {
				accent: cfg.accent ?? "#2783DE",
				wallpaper: wallpapers[cfg.wallpaper ?? "space"],
			},
			sizeMb: 40,
		}),
	},
	"app.browser": app("Internet", ["firefox-esr"], 260),
	"app.paint": app("Paint", ["pinta"], 120),
	"app.code": app("Code", ["codium"], 340),
	"identity.brand": {
		emit: (cfg) => ({
			files: [
				{
					path: "etc/zenvx/brand.conf",
					content: `TAGLINE="${cfg.tagline ?? ""}"\nLOGO=${cfg.logo ?? "rocket"}\n`,
				},
			],
			sizeMb: 1,
		}),
	},
	"identity.user": {
		emit: (cfg) => ({
			hooks: [
				`useradd -m -s /bin/bash ${cfg.username ?? "zen"} || true`,
				`usermod -aG sudo,audio,video ${cfg.username ?? "zen"} || true`,
			],
			files:
				cfg.autologin === false
					? []
					: [
						{
							path: "etc/lightdm/lightdm.conf.d/90-zenvx-autologin.conf",
							content: `[Seat:*]\nautologin-user=${cfg.username ?? "zen"}\nautologin-user-timeout=0\n`,
						},
					],
			sizeMb: 1,
		}),
	},
	"output.iso": {
		emit: (cfg) => ({
			lbFlags: { binary_images: "iso-hybrid" },
			packages: cfg.installer === false ? [] : ["calamares", "calamares-settings-debian"],
			sizeMb: cfg.installer === false ? 0 : 120,
		}),
	},
}

/* ---- compiler ----------------------------------------------------------- */
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "myos"

function compile(recipe) {
	const packages = new Set()
	const lbFlags = {}
	const hooks = []
	const services = new Set()
	const includes = []
	let sim = { panel: "bottom", accent: "#2783DE", desktopIcons: [] }
	let estimatedMb = 0

	for (const b of recipe.blocks) {
		const def = BLOCKS[b.def]
		if (!def) throw new Error(`unknown block: ${b.def}`)
		const c = def.emit(b.cfg ?? {})
		for (const p of c.packages ?? []) packages.add(p)
		Object.assign(lbFlags, c.lbFlags ?? {})
		for (const h of c.hooks ?? []) hooks.push(h)
		for (const s of c.services?.enable ?? []) services.add(s)
		for (const f of c.files ?? []) includes.push(f)
		if (c.sim) {
			const { desktopIcons = [], ...rest } = c.sim
			sim = { ...sim, ...rest, desktopIcons: [...sim.desktopIcons, ...desktopIcons] }
		}
		estimatedMb += c.sizeMb ?? 0
	}

	const id = slug(recipe.name)
	const files = []

	const flagLines = Object.entries(lbFlags)
		.map(([k, v]) => `  --${k.replace(/_/g, "-")} "${v}" \\`)
		.join("\n")

	files.push({
		path: "auto/config",
		mode: "755",
		content: `#!/bin/sh\n# Generated by ZenvX Framework. Do not edit by hand.\nset -e\n\nlb config noauto \\\n${flagLines}\n  --iso-application "${recipe.name}" \\\n  --iso-volume "${recipe.name}" \\\n  "\${@}"\n`,
	})

	files.push({
		path: "build.sh",
		mode: "755",
		content: `#!/bin/sh\nset -e\nlb clean --purge\n./auto/config\nlb build 2>&1 | tee build.log\n`,
	})

	files.push({
		path: "config/package-lists/zenvx.list.chroot",
		content: `${[...packages].sort().join("\n")}\n`,
	})

	files.push({
		path: "config/includes.chroot/etc/os-release",
		content: [
			`NAME="${recipe.name}"`,
			`PRETTY_NAME="${recipe.name}${recipe.codename ? ` (${recipe.codename})` : ""}"`,
			`ID=${id}`,
			`ID_LIKE=debian`,
			`VERSION="0.1"`,
			`HOME_URL="https://zenvx.dev/distros/${id}"`,
			`BUILD_ID="zenvx-framework"`,
			"",
		].join("\n"),
	})

	files.push({
		path: "config/includes.chroot/etc/zenvx/recipe.json",
		content: `${JSON.stringify(recipe, null, 2)}\n`,
	})

	for (const f of includes) {
		files.push({ path: `config/includes.chroot/${f.path}`, content: f.content })
	}

	const hookLines = [
		"#!/bin/sh",
		"# Generated by ZenvX Framework.",
		"set -e",
		"",
		...hooks,
		...[...services].map((s) => `systemctl enable ${s} || true`),
		"",
	]
	files.push({
		path: "config/hooks/normal/9000-zenvx.hook.chroot",
		mode: "755",
		content: hookLines.join("\n"),
	})

	return { files, packages: [...packages].sort(), lbFlags, sim, estimatedMb }
}

/* ---- write it out ------------------------------------------------------- */
const out = compile(recipe)
await rm(OUT, { recursive: true, force: true })
for (const f of out.files) {
	const target = join(OUT, f.path)
	await mkdir(dirname(target), { recursive: true })
	await writeFile(target, f.content, "utf8")
	if (f.mode) await chmod(target, parseInt(f.mode, 8))
}
await writeFile(
	join(OUT, "zenvx-preview.json"),
	`${JSON.stringify({ name: recipe.name, sim: out.sim, estimatedMb: out.estimatedMb }, null, 2)}\n`,
	"utf8",
)

console.log(`${recipe.name} (${recipe.codename ?? "-"})`)
console.log(`  blocks     ${recipe.blocks.length}`)
console.log(`  packages   ${out.packages.length}`)
console.log(`  est. size  ${(out.estimatedMb / 1024).toFixed(2)} GB`)
console.log(`  files      ${out.files.length} -> demo/aaruos`)
for (const f of out.files) console.log(`             ${f.path}`)
